name: CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:lts-trixie

    steps:
    - uses: actions/checkout@v7
    - name: publish
      run: |
        apt update
        npm install
        npm run compile
        npm run lint
        npm install -g @vscode/vsce typescript
        bash tools/conditional-publish.bash
      env:
        PUBLISH_SECRET: ${{ secrets.VSCODE_API_KEY }}

